/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */

/*  
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.codename1.charts.util.ColorUtil;
import com.codename1.components.ImageViewer;
import com.codename1.components.SpanLabel;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.ui.Button;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.InfiniteContainer;
import com.codename1.ui.List;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.list.MultiList;
import com.codename1.ui.table.DefaultTableModel;
import com.codename1.ui.table.Table;
import com.codename1.ui.table.TableModel;
import com.codename1.ui.util.UIBuilder;
import entity.Commande;
import service.CommandeService;
import java.util.ArrayList;
import com.mycompany.myapp.MyApplication;
import com.codename1.ui.Form;
import com.codename1.ui.Image;
import entity.Annonce;

/**
 *
 * @author Hussam
 */
public class AffichageAnnonce {

    private Form form;
    private Resources theme;

    public AffichageAnnonce() {
        AffichageCom affCom = new AffichageCom();

        //form statique
        form = new Form("Annonce", BoxLayout.y());
        form.getToolbar().addCommandToSideMenu("Home", null , ev ->{  
        });
        
        form.getToolbar().addCommandToSideMenu("login", null , ev ->{ 
            
        });
        
        form.getToolbar().addCommandToSideMenu("Events", null , ev ->{  
            
            
        });
        
        form.getToolbar().addCommandToSideMenu("My Orders", null , ev ->{  
            affCom.getF().show();
            
        });
        
        form.getToolbar().addCommandToSideMenu("Events & Participants", null , ev ->{  
//            
            
        });
        
        form.getToolbar().addCommandToSideMenu("MY Events", null , ev ->{  
            
            
        });
        
        form.getToolbar().addCommandToSideMenu("Annonce", null , ev ->{  
            
        });
        form.getToolbar().addCommandToSideMenu("MyReclaims", null , ev ->{ 
//                         gui.MyReclaimsFrom rec = new gui.MyReclaimsFrom();
//                         rec.getForm().show();
                 
        });
        form.getToolbar().addCommandToSideMenu("Comments", null , ev ->{ 
            
            
        });
        
        CommandeService ser = new CommandeService();
        ArrayList<Annonce> annonces = new ArrayList<>();
        annonces = ser.getList5();
        
        for (int i = 0 ; i<annonces.size()-1; i++){
            Image img;
        try {
            img = Image.createImage("/"+Integer.toString(i+8)+".jpg");
            
            form.add(img);
        } catch (IOException ex) {

        }
        form.add(new Label(annonces.get(i).getTitre()));
        form.add(new Label(annonces.get(i).getDescription()));
        form.add(new Label(Float.toString(annonces.get(i).getPrix())));
        Button ajouterP = new Button("Add to cart");
        Button troquer = new Button("Exchange");
        ajouterP.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                //add to cart
                ser.addToCart(8);
                Dialog.show("Cart", "Added successfully to cart", "OK", "");
                AffichageCom affcom = new AffichageCom();
                affCom.getF().show();
            }
        });
        
        troquer.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                Form annonces = new Form("My Product List", BoxLayout.y());
                form.getToolbar().addCommandToSideMenu("Home", null , ev ->{  
        });
        
        form.getToolbar().addCommandToSideMenu("login", null , ev ->{ 
            
        });
        
        form.getToolbar().addCommandToSideMenu("My Orders", null , ev ->{  
            affCom.getF().show();
            
        });
        
        form.getToolbar().addCommandToSideMenu("Events", null , ev ->{  
            
            
        });
        
        form.getToolbar().addCommandToSideMenu("Events & Participants", null , ev ->{  
//            
            
        });
        
        form.getToolbar().addCommandToSideMenu("MY Events", null , ev ->{  
            
            
        });
        
        form.getToolbar().addCommandToSideMenu("Annonce", null , ev ->{  
            
        });
        form.getToolbar().addCommandToSideMenu("MyReclaims", null , ev ->{ 
//                         gui.MyReclaimsFrom rec = new gui.MyReclaimsFrom();
//                         rec.getForm().show();
                 
        });
        form.getToolbar().addCommandToSideMenu("Comments", null , ev ->{ 
            
            
        });
                //Affichage liste de mes annonecs
                Container c1 = new Container(new BoxLayout(BoxLayout.X_AXIS));
                Image img;
                try {
                    img = Image.createImage("/2.jpg");
                    c1.add(img);
                } catch (IOException ex) {

                }
                Container c2 = new Container(new BoxLayout(BoxLayout.Y_AXIS));
                Label name = new Label("Annonce 2");
                Label price = new Label("20 DT");
                Label description = new Label("Description 2");
                Button confirmExchange = new Button("Confirm");
                confirmExchange.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent evt) {
                        ser.troc(8, 9);
                        Dialog.show("Exchange", "Your exchange request have been sent", "OK", "");
                        form.show();
                    }
                });
                //adding the containers
                //c1.setLeadComponent(name);
                c2.add(name);
                c2.add(description);
                c2.add(confirmExchange);
                //c1.add(img);
                c1.add(c2);
                annonces.add(c1);
                annonces.show();
            }
        });
        form.add(ajouterP);
        form.add(troquer);
        //form.add(troquer);
    }
        
        

        
        
        
        //form.add(affichCommandes);
        form.show();
    }

    public Form getF() {
        return form;
    }

    public void setF(Form f) {
        this.form = f;
    }

}
